version: '2'
services:
    hagrid-app:
        image: hagrid
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hagrid-mysql:3306/hagrid?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hagrid-mysql:
        extends:
            file: mysql.yml
            service: hagrid-mysql
